version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10
    working_directory: ~/ProjektArbeit-FIAE
    steps:
      - checkout

      - restore_cache:
          key: node_modules-{{ checksum "package-lock.json" }}

      - run:
          name: installing expo-cli
          command: npm install -D expo-cli

      - run:
          name: installing packages
          command: npm install

      - save_cache:
          key: node_modules-{{ checksum "package-lock.json" }}
          paths:
            - ~/.cache/npm

      - run:
          name: Expo Login & Build
          command: |
            npx expo login -u $ExpoLogin -p $ExpoPassword &&
            npx expo build:android --release-channel $ReleaseChannel --no-publish --non-interactive
      - persist_to_workspace:
          root: ~/ProjektArbeit-FIAE
          paths:
            - node_modules

  test:
    docker:
      - image: circleci/node:10
    working_directory: ~/ProjektArbeit-FIAE
    steps:
      - checkout

      - attach_workspace:
          at: ~/ProjektArbeit-FIAE

      - restore_cache:
          key: node_modules-{{ checksum "package-lock.json" }}

      - run:
          name: tsc type-checking && eslint
          command: |
            npm i -D eslint@5.16.0 &&
            npm i -D babel-eslint@10.0.2 &&
            npm i -D eslint-plugin-react@7.14.2 &&
            npm i -D eslint-plugin-react-native@3.7.0 &&
            npx eslint ./ && npx typescript -p ./tsconfig.json
workflows:
  version: 2.1
  android-build-test:
    jobs:
      - test
      - build:
          requires:
            - test
